### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by mateuscruz** [we-cli/coverage-badge-action#4]
Hello! 

First of all, thanks for building this!

Although it looks useful and super easy to use, legally speaking, no one is allowed to use it without a proper license, which is missing from this repo.

Could you add a license to your repo (preferably [MIT](https://opensource.org/license/mit))? 

http://opensource.stackexchange.com/q/1720/775

Thanks!

**Comment by fritx** [comment]
@mateuscruz tks for suggestion. Just added the MIT license, is it okay now?

**Comment by mateuscruz** [comment]
Yes it is! Thank you very much.
